# -*- coding: utf-8 -*-
"""ex 4_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vvxMrCP82_zumWri-Sl8CR6OJwknEInS
"""

# Exercise 4.3

from matplotlib import pyplot as plt
import math

Z_1 = complex(3, 5)
Z_2 = complex(5, -6)
Z_0 = complex(2, 3)

E = complex(100, 0)

Z_12 = 1/(1/Z_1+1/Z_2)
Z_tot = Z_0 + Z_12
print(Z_tot)

# Compute currents.
I = E/Z_tot

print(I)
V_12 = Z_0 * I
V_23 = Z_12 * I
test = V_12 + V_23
print(test)
I_Z1 = V_23 / Z_1
I_Z2 = I - I_Z1

print("V_12 = %s" % V_12)
print("V_23 = %s" % V_23)

print("I = %s" % I)
print("I_Z1 = %s" % I_Z1)
print("I_Z2 = %s" % I_Z2)


# Plot voltages.
f, (ax1, ax2) = plt.subplots(1, 2)
for U in [E, V_12, V_23]:
    ax1.plot([0, U.real], [0, U.imag], marker='o')
#ax1.set_xlim((0, 110))
#ax1.set_ylim((-50, 50))
ax1.set_ylabel('Imaginary')
ax1.set_xlabel('Real')

# Plot currents.
for i in [I, I_Z1, I_Z2]:
    ax2.plot([0, i.real], [0, i.imag], marker='o')
#ax2.set_xlim((0, 0.04))
#ax2.set_ylim((-0.02, 0.02))
ax2.set_ylabel('Imaginary')
ax2.set_xlabel('Real')

plt.show()